# This workflow generates the experimental catalog and pushes it to
# the publish branch.
name: generate-experimental-catalog

on:
  workflow_dispatch: # allow manual triggering
  schedule:
    - cron: '0 1 * * *'

jobs:
  generate-catalog:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'openshift-pipelines' # do not run this elsewhere
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
    - name: Generate experimental catalog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go run ./cmd/catalog-cd generate --config ./experimental/externals.yaml experimental
    - uses: actions/upload-artifact@v3
      with:
        name: experimental-catalog-artifact
        path: experimental/
        retention-days: 3 # We don't need to keep them for long

  publish-catalog:
    runs-on: ubuntu-latest
    needs: generate-catalog
    if: github.repository_owner == 'openshift-pipelines' # do not run this elsewhere
    steps:
    - name: Checkout "p" publish branch
      uses: actions/checkout@v3
      with:
        ref: p
    - name: Fetch generated experimental catalog
      uses: actions/download-artifact@v3
      with:
        name: experimental-catalog-artifact
    - name: Push catalog to publish branch
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add repos
          git commit -m "Auto-update packages"
          git pull --rebase --autostash
          git push



